import fs from 'fs';
import path from 'path';

import typescript from '@rollup/plugin-typescript';
import resolve from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';

// demo page specific imports
import alias from '@rollup/plugin-alias';
import copy from 'rollup-plugin-copy';
import serve from 'rollup-plugin-serve';
import livereload from 'rollup-plugin-livereload';

// Fixes broken sourcemaps generated by rollup which might mess up association to a sourcemap's bundle file when writing
// multiple outputs to the same directory, see https://github.com/rollup/rollup/issues/3439.
function fixSourcemaps() {
    return {
        name: 'fix-sourcemaps',
        generateBundle: (options, bundle) => {
            for (const assetOrChunkInfo of Object.values(bundle)) {
                if (!assetOrChunkInfo.map) return; // has no sourcemap
                assetOrChunkInfo.map.file = path.basename(assetOrChunkInfo.fileName);
            }
        },
    };
}

export default (commandLineArgs) => {
    const isServing = commandLineArgs.configServe; // called with --configServe?

    const lowLevelApiConfig = {
        input: 'src/low-level-api/low-level-api.ts',
        output: [
            {
                dir: 'dist', // not dist/low-level-api as ts plugin creates sub folder structure in dist as in rootDir
                format: 'es',
                entryFileNames: 'low-level-api/[name].[format].js',
                sourcemap: true,
                plugins: [
                    fixSourcemaps(),
                ]
            },
            {
                dir: 'dist',
                format: 'cjs',
                entryFileNames: 'low-level-api/[name].[format].js',
                sourcemap: true,
                plugins: [
                    fixSourcemaps(),
                ],
            },
        ],
        plugins: [
            typescript({
                include: ['src/low-level-api/**'],
                declaration: true,
                declarationDir: 'dist',
                rootDir: 'src', // temporary, see https://github.com/rollup/plugins/issues/61#issuecomment-596270901
                noEmitOnError: !isServing,
            }),
            resolve({ browser: true }), // use browser versions of packages if defined in their package.json
            commonjs(),
        ],
        watch: {
            clearScreen: false,
        },
    };

    const demoConfig = {
        input: 'src/demo/index.ts',
        output: {
            dir: 'dist/demo',
            format: 'es',
            sourcemap: true,
        },
        plugins: [
            typescript({
                include: ['src/demo/**', 'src/lib/**'],
                noEmitOnError: !isServing,
            }),
            // typescript needs 'low-level-api' to find the .d.ts file but for bundling we need to point to .es.js file
            alias({
                entries: {
                    '../../dist/low-level-api/low-level-api': '../../dist/low-level-api/low-level-api.es.js',
                },
            }),
            resolve(),
            commonjs({ namedExports: { 'u2f-api': ['sign', 'isSupported'] } }),
            copy({ targets: [{ src: 'src/demo/template.html', dest: 'dist/demo', rename: 'index.html' }] }),
        ],
        watch: {
            clearScreen: false,
        },
    };

    if (isServing) {
        // Taken from https://github.com/webpack/webpack-dev-server/commit/e97741c84ca69913283ae5d48cc3f4e0cf8334e3
        // Note that webpack-dev-server in the mean time switched to generating a separate certificate per project but
        // we don't need that here.
        const sslCertificate = fs.readFileSync('ssl/server.pem');
        const httpsOptions = {
            key: sslCertificate,
            cert: sslCertificate,
        };

        demoConfig.plugins = [
            ...demoConfig.plugins,
            serve({
                // list dist/demo to make index.html available at server root
                contentBase: ['dist', 'dist/demo'],
                // ledger transport apis require https.
                https: httpsOptions,
            }),
            livereload({
                watch: 'dist',
                https: httpsOptions,
            }),
        ]
    }

    return [lowLevelApiConfig, demoConfig];
}
